#!/bin/bash

CURR_LANG="$(setxkbmap -print | grep xkb_symbols | awk '{print $4}' | awk -F"+" '{print $2}')"
US="us"
INTL="us(intl)"
DE="de"

if [ $CURR_LANG == $INTL ]
then
	echo "INTL"
elif [ $CURR_LANG == $DE ]
then
	echo "DE"
elif [ $CURR_LANG == $US ]
then
	echo "US"
else
	echo "US"
fi
